### PR TITLE
fix: add thinking tokens to usage stats for gemini models

### LINKED ISSUE #3335: [JS] Add thought (reasoning) token "usage" counts to telemetry
Currently the Gemini API returns thought token "usage" counts, however, we're not capturing it and/or displaying it in the tooling. We need to show it, because it effects the price of API calls to Gemini, even in cases where thought tokens are not returned in the response.

Screenshot below from a trace shows that `usage` does not contain throught tokens, however the Gemini response `custom.usageMetadata` does.

Image

### PR DESCRIPTION
**Pull request by MichaelDoyle**
Fixes #3335

- Adds to genai plugin
- Backports to gemini & vertex plugins.

### CODE REVIEW

File: js/plugins/googleai/src/gemini.ts [hunk 1]
```diff
@@ -67,6 +68,10 @@ import { getApiKeyFromEnvVar } from './common';
 import { handleCacheIfNeeded } from './context-caching';
 import { extractCacheConfig } from './context-caching/utils';
 
+type ExtendedUsageMetadata = UsageMetadata & {
```
Comment (ifielker) [inline js/plugins/googleai/src/gemini.ts:71]: Why does this need to be a new type? What happens when we have another field, is it then ExtendedExtendedUsageMetadata? :)

File: js/plugins/vertexai/src/gemini.ts [hunk 2]
```diff
@@ -63,11 +64,14 @@ import {
 } from 'genkit/model/middleware';
 import { runInNewSpan } from 'genkit/tracing';
 import { GoogleAuth } from 'google-auth-library';
-
 import type { PluginOptions } from './common/types.js';
 import { handleCacheIfNeeded } from './context-caching/index.js';
 import { extractCacheConfig } from './context-caching/utils.js';
 
+type ExtendedUsageMetadata = UsageMetadata & {
```
Comment (ifielker) [inline js/plugins/vertexai/src/gemini.ts:71]: Same here

**Review by ifielker — CHANGES_REQUESTED** [review]

**Review by ifielker — APPROVED** [review]

File: js/plugins/google-genai/src/googleai/gemini.ts [hunk 3]
```diff
@@ -621,6 +621,7 @@ export function defineModel(
             ...getBasicUsageStats(request.messages, candidateData),
             inputTokens: response.usageMetadata?.promptTokenCount,
             outputTokens: response.usageMetadata?.candidatesTokenCount,
+            reasoningTokens: response.usageMetadata?.thoughtsTokenCount,
```
Comment (ifielker) [inline js/plugins/google-genai/src/googleai/gemini.ts]: This needs to match GenerationUsageSchema
so it needs to be  thoughtsTokens: z.number().optional(),

**Review by ifielker — CHANGES_REQUESTED** [review]

File: js/plugins/google-genai/src/googleai/gemini.ts (hunk 3 above)
Comment (MichaelDoyle) [reply js/plugins/google-genai/src/googleai/gemini.ts]: Done -- thanks!

**Review by schnecle — APPROVED** [review]
