### PR TITLE
Include model in options for executable prompts

### LINKED ISSUE #1119: [JS] model specified in .prompt is ignored
**Describe the bug**
the model specified in .prompt is ignored

**To Reproduce**

This .prompt file:

```
---
model: googleai/gemini-1.5-pro
---
You are the world's most welcoming AI assistant. Greet the user and offer your assistance.
```

Fails when run with:

```
const ai = genkit({
  plugins: [
    googleAI(),
  ],
});

const helloDotPrompt = ai.defineFlow(
    { name: "helloP" },
    async () => {
        const helloPrompt = await ai.prompt('hello');
        const { text } = await helloPrompt();
        return text;
    }
)

console.log(await helloDotPrompt());
```

Error:

```
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

Error: Model is required.
    at /Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:396:13
    at Generator.next (<anonymous>)
    at /Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:54:61
    at new Promise (<anonymous>)
    at __async (/Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:38:10)
    at resolveModel (/Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:393:10)
    at /Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:433:33
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevincheung/tmp/0.9-dev.1-test/node_modules/.pnpm/@genkit-ai+ai@0.9.0-dev.2/node_modules/@genkit-ai/ai/lib/generate.js:41:24)
```

Adding a default model to `genkit()` makes it work.

**Expected behavior**

**Screenshots**

**Runtime (please complete the following information):**
 - OS: [e.g. Linux, MacOS]

** Node version
 -  run `node --version` at paste here

**Additional context**

### PR DESCRIPTION
**Pull request by MichaelDoyle**
When wrapping prompt actions as ExecutablePrompt, we need to include the model in the options. This is because the PromptAction returns GenerateRequest, which in turn does not actually include model. This is particularly a problem for dotprompt files.

Checklist (if applicable):
- [x] Tested (manually, unit tested, etc.)
- [NA] Docs updated

cc @pavelgj 

Fixes #1119

### CODE REVIEW

File: js/genkit/src/genkit.ts [hunk 1]
```diff
@@ -279,18 +279,12 @@ export class Genkit {
...
-    // check if functional prompt exists.
-    let action = (await this.registry.lookupAction(
-      `/prompt/${name}`
-    )) as PromptAction<I>;
-    // if not, lookup with dotprompt.
-    if (!action) {
-      action = (await prompt(this.registry, name, options))
-        .promptAction as PromptAction<I>;
-    }
+    const dotprompt = await prompt(this.registry, name, options);
```
Comment (pavelgj) [inline js/genkit/src/genkit.ts:282]: The problem is this function can load dotprompt prompts from the registry ONLY. It will fail loading functional prompts.

**Comment by MichaelDoyle** [comment]
Updated per @pavelgj and added a bit more color to the comments in the code to describe more clearly what is happening.

**Review by maxl0rd — APPROVED** [review]
