### PR TITLE
fix: log error with duplicate action key

### LINKED ISSUE #26: Duplicate names in `defineFlow` overrides the original definition rather than failing.

### PR DESCRIPTION
**Pull request by gioboa**
This commit change the behavior with actions with the same name.
Based on the issue description I changed warnings into errors.

Close #26 

Checklist (if applicable):
- [X] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [X] Tested (manually, unit tested, etc.)
- [ ] Docs updated (updated docs or a docs bug required)

### CODE REVIEW

**Comment by MichaelDoyle** [comment]
Hey @gioboa - just checking - it looks like this PR only changes the "log level" from warning to error, and does not actually raise any error. Based on the PR title, though, I think you intend to throw an error?

**Comment by gioboa** [comment]
> Hey @gioboa - just checking - it looks like this PR only changes the "log level" from warning to error, and does not actually raise any error. Based on the PR title, though, I think you intend to throw an error?

Yep, you are right. I fixed the code to get the desired behavior.

**Comment by gioboa** [comment]
Thanks for your review @MichaelDoyle 
I'm looking forward to getting your feedback about the change.

**Comment by gioboa** [comment]
@pavelgj Can you review this simple change please?

File: js/core/src/registry.ts [hunk 1]
```diff
@@ -291,9 +291,8 @@ export class Registry {
     const key = `/${type}/${action.__action.name}`;
     logger.debug(`registering ${key}`);
     if (this.actionsById.hasOwnProperty(key)) {
-      // TODO: Make this an error!
-      logger.warn(
-        `WARNING: ${key} already has an entry in the registry. Overwriting.`
+      logger.error(
+        `Failed to register ${key} action because it's already in the registry.`
```
Comment (pavelgj) [inline js/core/src/registry.ts]: this message is not accurate -- `logger.error` does not throw an error, it just logs at "error" log level, so it would not fail to register a duplicate key. 

I'm not sure if we can actually make this throw an error at this point... I know for sure there would need to be a number of tests that will need fixing.

s/logger.warn/logger.error/ is a good idea and a low risk change.

Comment (gioboa) [reply js/core/src/registry.ts]: I see, I changed the message to `ERROR`.

**Review by pavelgj — APPROVED** [review]
