### PR TITLE
fix: made ai.prompt sync

### LINKED ISSUE #1152: [JS] ai.prompt should be sync
In `0.5.x` `promptRef` allowed sync references to prompts that could then be executed. This is how `ai.prompt` should behave, as async references are obnoxious.

```ts
// right now in `next`
const {output} = await (await ai.prompt('myPrompt'))({input: 'here'});

// it should be...
const {output} = await ai.prompt('myPrompt')({input: 'here'});
```

This is even more important to be able to set up prompt refs outside of async function bodies since top-level await is a footgun.

### PR DESCRIPTION
**Pull request by pavelgj**
Fixes #1152

### CODE REVIEW

File: js/genkit/src/genkit.ts [hunk 1]
```diff
@@ -271,29 +271,33 @@ export class Genkit {
...
+      // check the registry first as not all prompt types can be
+      // loaded by dotprompt (e.g. functional)
+      let action = (await this.registry.lookupAction(
+        `/prompt/${name}`
+      )) as PromptAction<I>;
+      // nothing in registry - check for dotprompt file.
+      if (!action) {
+        action = (await prompt(this.registry, name, options))
+          .promptAction as PromptAction<I>;
+      }
```
Comment (mbleigh) [inline js/genkit/src/genkit.ts:292]: You might want to look at `promptRef` and its implementation...I believe it also accounted for reloading prompts when the files changed but don't remember for sure.

Comment (pavelgj) [reply js/genkit/src/genkit.ts:292]: I think it's conceptually similar...

**Review by mbleigh — APPROVED** [review]
We can work on reloading prompts in dev mode as a followup if needed.

**Review by apascal07 — APPROVED** [review]
