### PR TITLE
Makes inputSchema optional for tools.

### LINKED ISSUE #814: [Tooling] Tools fail if defined without arguments
**Describe the bug**

I have a simple tool that returns some data from a database. It does not need an argument. As a result of not having an argument, it fails in ways that are hard to debug. 

When invoking the tool directly in the dev ui, it works appropriately.

However, when used in a flow. the tool (with no input schema) errors with: 

`INVALID_ARGUMENT: Schema validation failed. Parse Errors: - tools.2.inputSchema: must be object `

with z.object({}), it errors in the flow and direct invocation with:
- flow:
`[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent: [400 Bad Request] * GenerateContentRequest.tools[0].function_declarations[2].parameters.properties: should be non-empty for OBJECT type`

- tool:
`TRPCClientError: INVALID_ARGUMENT: Schema validation failed. Parse Errors:

- (root): must be object`

with z.any() the tool works, and returns a populated object, but the flow errors with 

`Cannot read properties of undefined (reading 'toUpperCase')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at convertSchemaProperty (/Users/connor/fora-echo/node_modules/@genkit-ai/googleai/lib/gemini.js:234:78)`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - mac OS: 14.4 (23E214)

### PR DESCRIPTION
**Pull request by mbleigh**
Fixes #814 and also fixes a nasty regression with the new `generateAction` that caused `response.toHistory()` to stop working.

There's still an issue with tool calling and `toHistory`, which is that the tool request / responses are elided from history once the LLM comes back with a full response. We should fix that.

Checklist (if applicable):
- [x] Tested (manually, unit tested, etc.)

### CODE REVIEW

File: js/ai/src/generate.ts [hunk 1]
```diff
@@ -610,7 +610,11 @@ export async function generate<
 
   return await runWithStreamingCallback(
     resolvedOptions.streamingCallback,
-    async () => new GenerateResponse<O>(await generateAction(params))
+    async () =>
+      new GenerateResponse<O>(
```
Comment (pavelgj) [inline js/ai/src/generate.ts:614]: Do you mind adding a quick unit test for this?

**Review by pavelgj — APPROVED** [review]

File: js/ai/src/generate.ts (hunk 1 above)
Comment (mbleigh) [reply js/ai/src/generate.ts:614]: Done.
